apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: deploy-test
  template:
    metadata:
      labels:
        app: deploy-test
